# Generated by Django 2.2.11 on 2020-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='welcome_sent',
            field=models.BooleanField(default=False),
        ),
    ]
