# Generated by Django 2.2.11 on 2020-05-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_welcome_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='welcome_sent',
        ),
    ]
