# Generated by Django 2.2.11 on 2020-05-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_isvet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isvet',
            field=models.BooleanField(default=False, null='True'),
        ),
    ]
