# Generated by Django 2.2.11 on 2020-05-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200508_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isvet',
            field=models.BooleanField(blank='True', default=False, null='True'),
        ),
    ]
