# Generated by Django 2.2.5 on 2020-03-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('full_address', models.CharField(max_length=2048)),
                ('longitude', models.CharField(max_length=64)),
                ('latitude', models.CharField(max_length=64)),
            ],
        ),
    ]
