# Generated by Django 2.2.5 on 2020-03-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_veterinary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinary',
            old_name='latitude',
            new_name='postcode',
        ),
        migrations.RemoveField(
            model_name='veterinary',
            name='longitude',
        ),
    ]
