# Generated by Django 2.2.5 on 2020-03-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='cat',
        ),
    ]
