# Generated by Django 2.2.11 on 2020-04-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_expense_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinary',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='veterinary',
            name='postcode',
        ),
    ]
