# Generated by Django 2.2.11 on 2020-04-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200430_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
