# Generated by Django 2.2.11 on 2020-04-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_veterinary_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinary',
            name='rating',
        ),
    ]
