# Generated by Django 2.2.11 on 2020-05-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_veterinary_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.IntegerField(default=5)),
                ('review_text', models.CharField(max_length=1024)),
                ('vet_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Veterinary')),
            ],
        ),
    ]
