# Generated by Django 2.2.11 on 2020-05-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
