# Generated by Django 2.2.11 on 2020-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_veterinary_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(default='catphotodefault.jpg', height_field='picture_height', max_length=128, upload_to='catphotos/', width_field='picture_width'),
        ),
    ]
