# Generated by Django 2.2.11 on 2020-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200503_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(default='static/catprofile.png', height_field='picture_height', max_length=128, upload_to='catphotos/', width_field='picture_width'),
        ),
    ]
