# Generated by Django 2.2.11 on 2020-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200503_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='Spayed_Neutred',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='microchip_number',
            field=models.CharField(max_length=15),
        ),
    ]
