# Generated by Django 2.2.11 on 2020-05-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200503_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(default='static/catprofile.png', max_length=128, upload_to='catphotos/'),
        ),
    ]
