# Generated by Django 2.2.11 on 2020-05-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200503_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='insurance_provider',
            field=models.CharField(choices=[('Argos Pet Insurance', 'Argos Pet Insurance'), ('Agria Pet Insurance', 'Agria Pet Insurance'), ('Animal Friends Pet Insurance', 'Animal Friends Pet Insurance'), ('ASPCA Pet Health Insurance', 'ASPCA Pet Health Insurance'), ('Bought By Many Pet Insurance', 'Bought By Many Pet Insurance'), ('Direct Line Pet Insurance', 'Direct Line Pet Insurance'), ('Embrace Pet Insurance', 'Embrace Pet Insurance'), ('FIGO Pet Insurance', 'FIGO Pet Insurance'), ('Healthypaws Pet Insurance & Foundation', 'Healthypaws Pet Insurance & Foundation'), ('Hartville Pet Insurance', 'Hartville Pet Insurance'), ('John Lewis Pet Insurance', 'John Lewis Pet Insurance'), ('More Than Pet Insurance', 'More Than Pet Insurance'), ('M&S Pet Insurance', 'M&S Pet Insurance'), ('PetPlan', 'PetPlan'), ('Pet-insurance.co.uk Pet Insurance', 'Pet-insurance.co.uk Pet Insurance'), ('Pets Best Pet Health Insurance', 'Pets Best Pet Health Insurance'), ('Petfirst Pet Insurance', 'Petfirst Pet Insurance'), ('Pet Assure', 'Pet Assure'), ('Sainsbury’s Pet Insurance', 'Sainsbury’s Pet Insurance'), ('The Insurance Emporium Pet Insurance', 'The Insurance Emporium Pet Insurance'), ('Tesco Pet Insurance', 'Tesco Pet Insurance'), ('Trupanion', 'Trupanion'), ('Waggel Pet Insurance', 'Waggel Pet Insurance'), ('4Paws Pet Insurance', '4Paws Pet Insurance')], max_length=64),
        ),
    ]
