# Generated by Django 2.2.11 on 2020-05-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200503_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(max_length=128, upload_to='catphotos/'),
        ),
    ]
