# Generated by Django 2.2.11 on 2020-05-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200503_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to='catphotos/'),
        ),
    ]
