# Generated by Django 2.2.11 on 2020-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200504_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
