# Generated by Django 2.2.11 on 2020-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200504_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_breed',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_weight_unit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cat',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
