# Generated by Django 2.2.11 on 2020-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200504_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='Spayed_Neutred',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_breed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
