# Generated by Django 2.2.11 on 2020-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200504_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='Spayed_Neutred',
            field=models.BooleanField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
    ]
