# Generated by Django 2.2.11 on 2020-05-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200504_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='Spayed_Neutred',
            new_name='Spayed_Neutered',
        ),
    ]
