# Generated by Django 2.2.11 on 2020-05-04 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200504_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_breed',
            field=models.CharField(default='unknown', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=8),
            preserve_default=False,
        ),
    ]
