# Generated by Django 2.2.11 on 2020-05-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200504_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='Spayed_Neutered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
