# Generated by Django 2.2.11 on 2020-05-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200504_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_weight_unit',
            field=models.CharField(default='Kg', max_length=16),
            preserve_default=False,
        ),
    ]
