# Generated by Django 2.2.11 on 2020-05-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200505_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_breed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
