# Generated by Django 2.2.11 on 2020-05-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200505_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cat_image'),
        ),
    ]
