# Generated by Django 2.2.11 on 2020-05-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200505_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='cats/%Y/%m/%d/'),
        ),
    ]
