# Generated by Django 2.2.11 on 2020-05-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200505_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='imagename',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='imageurl',
        ),
    ]
