# Generated by Django 2.2.11 on 2020-05-05 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200505_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='recordDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
