# Generated by Django 2.2.11 on 2020-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_medicalrecord_recorddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_email',
            field=models.BooleanField(default=False),
        ),
    ]
