# Generated by Django 2.2.11 on 2020-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_reminder_reminder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_repeat',
            field=models.CharField(default='Repeat (Off)', max_length=128),
        ),
    ]
