# Generated by Django 2.2.11 on 2020-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_reminder_reminder_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_repeat',
            field=models.CharField(choices=[('Repeat (Off)', 'Repeat (Off)'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Repeat (Off)', max_length=128),
        ),
    ]
