# Generated by Django 2.2.11 on 2020-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200506_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
    ]
