# Generated by Django 2.2.12 on 2020-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_cat_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='imagename',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='cat',
            name='imageurl',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
