# Generated by Django 2.2.11 on 2020-05-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200507_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reminder_repeat',
            field=models.CharField(choices=[('Repeat (Off)', 'Repeat (Off)'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Repeat (Off)', max_length=128),
        ),
    ]
