# Generated by Django 2.2.11 on 2020-05-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_expense_reminder_repeat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='reminder_repeat',
            new_name='expense_repeat',
        ),
    ]
